version: "3.8"

services:

  wwi-app:
    build:
      context: ./wwi-app
      dockerfile: Dockerfile
    container_name: wwi_app
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__WWI: "Host=postgres_15.1;Database=postgres;Username=postgres;Password=postgres;Application Name=WideWorldImporters"
    ports:
      - "3000:80"
    networks:
      - wwi-net
      - agentomatic

networks:
  wwi-net:
    driver: bridge
  agentomatic:
    external: true
    name: appz-images_agentomatic_net
