DO $body$
DECLARE
    v_currentdatetime timestamp := '2020-01-01';
    v_endoftime timestamp := '99991231 23:59:59.9999999';
    v_supplieridphoneco integer := NULL;
    v_supplieridgdi integer := NULL;
    v_supplieridnorthwind integer := NULL;
    v_supplieridfabrikam integer := NULL;
    v_supplieridcontoso integer := NULL;
    v_supplieridlitware integer := NULL;
    v_packagetypeideach integer := NULL;
    v_packagetypeidcarton integer := NULL;
    v_packagetypeidpair integer := NULL;
    v_packagetypeidpacket integer := NULL;
    v_coloridwhite integer := NULL;
    v_coloridblack integer := NULL;
    v_coloridnone integer := NULL;
    v_coloridgreen integer := NULL;
    v_coloridred integer := NULL;
    v_coloridblue integer := NULL;
    v_coloridyellow integer := NULL;
    v_coloridpink integer := NULL;
    v_coloridgray integer := NULL;
    v_coloridlightbrown integer := NULL;
    v_coloridbrown integer := NULL;
    v_coloridnull integer := NULL;
BEGIN
-- Rather than looking up some of these IDs on every row,
-- we'll look them up once at the start
-- Fetch Supplier IDs

SELECT SupplierID INTO v_supplieridphoneco FROM purchasing.suppliers WHERE SupplierName = 'The Phone Company';
SELECT SupplierID INTO v_supplieridgdi FROM purchasing.suppliers WHERE SupplierName = 'Graphic Design Institute';
SELECT SupplierID INTO v_supplieridnorthwind FROM purchasing.suppliers WHERE SupplierName = 'Northwind Electric Cars';
SELECT SupplierID INTO v_supplieridfabrikam FROM purchasing.suppliers WHERE SupplierName = 'Fabrikam, Inc.';
SELECT SupplierID INTO v_supplieridcontoso FROM purchasing.suppliers WHERE SupplierName = 'Contoso, Ltd.';
SELECT SupplierID INTO v_supplieridlitware FROM purchasing.suppliers WHERE SupplierName = 'Litware, Inc.';

-- Package Types

SELECT PackageTypeID INTO v_packagetypeideach FROM warehouse.packagetypes WHERE PackageTypeName = 'Each';
SELECT PackageTypeID INTO v_packagetypeidcarton FROM warehouse.packagetypes WHERE PackageTypeName = 'Carton';
SELECT PackageTypeID INTO v_packagetypeidpair FROM warehouse.packagetypes WHERE PackageTypeName = 'Pair';
SELECT PackageTypeID INTO v_packagetypeidpacket FROM warehouse.packagetypes WHERE PackageTypeName = 'Packet';

-- Colors

SELECT ColorID INTO v_coloridwhite FROM warehouse.colors WHERE ColorName = 'White';
SELECT ColorID INTO v_coloridblack FROM warehouse.colors WHERE ColorName = 'Black';
SELECT ColorID INTO v_coloridnone FROM warehouse.colors WHERE ColorName = '';
SELECT ColorID INTO v_coloridgreen FROM warehouse.colors WHERE ColorName = 'Green';
SELECT ColorID INTO v_coloridred FROM warehouse.colors WHERE ColorName = 'Red';
SELECT ColorID INTO v_coloridblue FROM warehouse.colors WHERE ColorName = 'Blue';
SELECT ColorID INTO v_coloridyellow FROM warehouse.colors WHERE ColorName = 'Yellow';
SELECT ColorID INTO v_coloridpink FROM warehouse.colors WHERE ColorName = 'Pink';
SELECT ColorID INTO v_coloridgray FROM warehouse.colors WHERE ColorName = 'Gray';
SELECT ColorID INTO v_coloridlightbrown FROM warehouse.colors WHERE ColorName = 'Light Brown';
SELECT ColorID INTO v_coloridbrown FROM warehouse.colors WHERE ColorName = 'Brown';
SELECT ColorID INTO v_coloridnull FROM warehouse.colors WHERE ColorName = 'NULL';

INSERT INTO warehouse.stockitems
  (StockItemID, StockItemName, SupplierID, ColorID,  UnitPackageID, OuterPackageID, Brand, Size, LeadTimeDays, QuantityPerOuter, IsChillerStock, Barcode, TaxRate, UnitPrice, RecommendedRetailPrice, TypicalWeightPerUnit, MarketingComments, InternalComments, Photo, CustomFields, LastEditedBy, ValidFrom, ValidTo)
VALUES
  (1,'USB missile launcher (Green)', v_supplieridphoneco, v_coloridgreen, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 14, 1, false, NULL, 15,25,37.38,0.3,'Complete with 12 projectiles', NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (2,'USB rocket launcher (Gray)', v_supplieridphoneco, v_coloridgray, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 14, 1, false, NULL, 15,25,37.38,0.3,'Complete with 12 projectiles', NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (3,'Office cube periscope (Black)', v_supplieridphoneco, v_coloridblack, v_packagetypeideach, v_packagetypeidcarton, NULL, NULL, 14, 10, false, NULL, 15, 18.5,27.66,0.25,'Need to see over your cubicle wall? This is just what''s needed.', NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (4,'USB food flash drive - sushi roll', v_supplieridphoneco, v_coloridnone, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 14, 1, false, NULL, 15,32,47.84,0.05, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (5,'USB food flash drive - hamburger', v_supplieridphoneco, v_coloridnone, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 14, 1, false, NULL, 15,32,47.84,0.05, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (6,'USB food flash drive - hot dog', v_supplieridphoneco, v_coloridnone, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 14, 1, false, NULL, 15,32,47.84,0.05, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (7,'USB food flash drive - pizza slice', v_supplieridphoneco, v_coloridnone, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 14, 1, false, NULL, 15,32,47.84,0.05, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (8,'USB food flash drive - dim sum 10 drive variety pack', v_supplieridphoneco, v_coloridnone, v_packagetypeidpacket, v_packagetypeidpacket, NULL, NULL, 14, 1, false, NULL, 15,240,358.8,0.5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (9,'USB food flash drive - banana', v_supplieridphoneco, v_coloridnone, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 14, 1, false, NULL, 15,32,47.84,0.05, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (10,'USB food flash drive - chocolate bar', v_supplieridphoneco, v_coloridnone, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 14, 1, false, NULL, 15,32,47.84,0.05, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (11,'USB food flash drive - cookie', v_supplieridphoneco, v_coloridnone, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 14, 1, false, NULL, 15,32,47.84,0.05, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (12,'USB food flash drive - donut', v_supplieridphoneco, v_coloridnone, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 14, 1, false, NULL, 15,32,47.84,0.05, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (13,'USB food flash drive - shrimp cocktail', v_supplieridphoneco, v_coloridnone, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 14, 1, false, NULL, 15,32,47.84,0.05, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (14,'USB food flash drive - fortune cookie', v_supplieridphoneco, v_coloridnone, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 14, 1, false, NULL, 15,32,47.84,0.05, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (15,'USB food flash drive - dessert 10 drive variety pack', v_supplieridphoneco, v_coloridnone, v_packagetypeidpacket, v_packagetypeidpacket, NULL, NULL, 14, 1, false, NULL, 15,240,358.8,0.5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (16,'DBA joke mug - mind if I join you? (White)', v_supplieridgdi, v_coloridwhite, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (17,'DBA joke mug - mind if I join you? (Black)', v_supplieridgdi, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (18,'DBA joke mug - daaaaaa-ta (White)', v_supplieridgdi, v_coloridwhite, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (19,'DBA joke mug - daaaaaa-ta (Black)', v_supplieridgdi, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (20,'DBA joke mug - you might be a DBA if (White)', v_supplieridgdi, v_coloridwhite, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (21,'DBA joke mug - you might be a DBA if (Black)', v_supplieridgdi, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (22,'DBA joke mug - it depends (White)', v_supplieridgdi, v_coloridwhite, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (23,'DBA joke mug - it depends (Black)', v_supplieridgdi, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (24,'DBA joke mug - I will get you in order (White)', v_supplieridgdi, v_coloridwhite, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (25,'DBA joke mug - I will get you in order (Black)', v_supplieridgdi, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (26,'DBA joke mug - SELECT caffeine FROM mug (White)', v_supplieridgdi, v_coloridwhite, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (27,'DBA joke mug - SELECT caffeine FROM mug (Black)', v_supplieridgdi, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (28,'DBA joke mug - two types of DBAs (White)', v_supplieridgdi, v_coloridwhite, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (29,'DBA joke mug - two types of DBAs (Black)', v_supplieridgdi, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (30,'Developer joke mug - Oct 31 = Dec 25 (White)', v_supplieridgdi, v_coloridwhite, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (31,'Developer joke mug - Oct 31 = Dec 25 (Black)', v_supplieridgdi, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (32,'Developer joke mug - that''s a hardware problem (White)', v_supplieridgdi, v_coloridwhite, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (33,'Developer joke mug - that''s a hardware problem (Black)', v_supplieridgdi, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (34,'Developer joke mug - fun was unexpected at this time (White)', v_supplieridgdi, v_coloridwhite, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (35,'Developer joke mug - fun was unexpected at this time (Black)', v_supplieridgdi, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (36,'Developer joke mug - when your hammer is C++ (White)', v_supplieridgdi, v_coloridwhite, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (37,'Developer joke mug - when your hammer is C++ (Black)', v_supplieridgdi, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (38,'Developer joke mug - inheritance is the OO way to become wealthy (White)', v_supplieridgdi, v_coloridwhite, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (39,'Developer joke mug - inheritance is the OO way to become wealthy (Black)', v_supplieridgdi, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (40,'Developer joke mug - (hip, hip, array) (White)', v_supplieridgdi, v_coloridwhite, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (41,'Developer joke mug - (hip, hip, array) (Black)', v_supplieridgdi, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (42,'Developer joke mug - understanding recursion requires understanding recursion (White)', v_supplieridgdi, v_coloridwhite, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (43,'Developer joke mug - understanding recursion requires understanding recursion (Black)', v_supplieridgdi, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (44,'Developer joke mug - there are 10 types of people in the world (White)', v_supplieridgdi, v_coloridwhite, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (45,'Developer joke mug - there are 10 types of people in the world (Black)', v_supplieridgdi, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (46,'Developer joke mug - a foo walks into a bar (White)', v_supplieridgdi, v_coloridwhite, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (47,'Developer joke mug - a foo walks into a bar (Black)', v_supplieridgdi, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (48,'Developer joke mug - this code was generated by a tool (White)', v_supplieridgdi, v_coloridwhite, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (49,'Developer joke mug - this code was generated by a tool (Black)', v_supplieridgdi, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (50,'Developer joke mug - old C developers never die (White)', v_supplieridgdi, v_coloridwhite, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (51,'Developer joke mug - old C developers never die (Black)', v_supplieridgdi, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (52,'IT joke mug - keyboard not found � press F1 to continue (White)', v_supplieridgdi, v_coloridwhite, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (53,'IT joke mug - keyboard not found � press F1 to continue (Black)', v_supplieridgdi, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (54,'IT joke mug - that behavior is by design (White)', v_supplieridgdi, v_coloridwhite, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (55,'IT joke mug - that behavior is by design (Black)', v_supplieridgdi, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (56,'IT joke mug - hardware: part of the computer that can be kicked (White)', v_supplieridgdi, v_coloridwhite, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (57,'IT joke mug - hardware: part of the computer that can be kicked (Black)', v_supplieridgdi, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL, NULL, 12, 1, false, NULL, 15, 13, 19.44,0.15, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (58,'RC toy sedan car with remote control (Black) 1/50 scale', v_supplieridnorthwind, v_coloridblack, v_packagetypeideach, v_packagetypeideach,'Northwind','1/50 scale', 14, 1, false, NULL, 15,25,37.38, 1.5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (59,'RC toy sedan car with remote control (Red) 1/50 scale', v_supplieridnorthwind, v_coloridred, v_packagetypeideach, v_packagetypeideach,'Northwind','1/50 scale', 14, 1, false, NULL, 15,25,37.38, 1.5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (60,'RC toy sedan car with remote control (Blue) 1/50 scale', v_supplieridnorthwind, v_coloridblue, v_packagetypeideach, v_packagetypeideach,'Northwind','1/50 scale', 14, 1, false, NULL, 15,25,37.38, 1.5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (61,'RC toy sedan car with remote control (Green) 1/50 scale', v_supplieridnorthwind, v_coloridgreen, v_packagetypeideach, v_packagetypeideach,'Northwind','1/50 scale', 14, 1, false, NULL, 15,25,37.38, 1.5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (62,'RC toy sedan car with remote control (Yellow) 1/50 scale', v_supplieridnorthwind, v_coloridyellow, v_packagetypeideach, v_packagetypeideach,'Northwind','1/50 scale', 14, 1, false, NULL, 15,25,37.38, 1.5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (63,'RC toy sedan car with remote control (Pink) 1/50 scale', v_supplieridnorthwind, v_coloridpink, v_packagetypeideach, v_packagetypeideach,'Northwind','1/50 scale', 14, 1, false, NULL, 15,25,37.38, 1.5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (64,'RC vintage American toy coupe with remote control (Red) 1/50 scale', v_supplieridnorthwind, v_coloridred, v_packagetypeideach, v_packagetypeideach,'Northwind','1/50 scale', 14, 1, false, NULL, 15,30,44.85, 1.7, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (65,'RC vintage American toy coupe with remote control (Black) 1/50 scale', v_supplieridnorthwind, v_coloridblack, v_packagetypeideach, v_packagetypeideach,'Northwind','1/50 scale', 14, 1, false, NULL, 15,30,44.85, 1.7, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (66,'RC big wheel monster truck with remote control (Black) 1/50 scale', v_supplieridnorthwind, v_coloridblack, v_packagetypeideach, v_packagetypeideach,'Northwind','1/50 scale', 14, 1, false, NULL, 15,45,67.28, 1.8, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (67,'Ride on toy sedan car (Black) 1/12 scale', v_supplieridnorthwind, v_coloridblack, v_packagetypeideach, v_packagetypeideach,'Northwind','1/12 scale', 14, 1, false, NULL, 15,230,343.85, 15,'Suits child to 20 kg', NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (68,'Ride on toy sedan car (Red) 1/12 scale', v_supplieridnorthwind, v_coloridred, v_packagetypeideach, v_packagetypeideach,'Northwind','1/12 scale', 14, 1, false, NULL, 15,230,343.85, 15,'Suits child to 20 kg', NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (69,'Ride on toy sedan car (Blue) 1/12 scale', v_supplieridnorthwind, v_coloridblue, v_packagetypeideach, v_packagetypeideach,'Northwind','1/12 scale', 14, 1, false, NULL, 15,230,343.85, 15,'Suits child to 20 kg', NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (70,'Ride on toy sedan car (Green) 1/12 scale', v_supplieridnorthwind, v_coloridgreen, v_packagetypeideach, v_packagetypeideach,'Northwind','1/12 scale', 14, 1, false, NULL, 15,230,343.85, 15,'Suits child to 20 kg', NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (71,'Ride on toy sedan car (Yellow) 1/12 scale', v_supplieridnorthwind, v_coloridyellow, v_packagetypeideach, v_packagetypeideach,'Northwind','1/12 scale', 14, 1, false, NULL, 15,230,343.85, 15,'Suits child to 20 kg', NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (72,'Ride on toy sedan car (Pink) 1/12 scale', v_supplieridnorthwind, v_coloridpink, v_packagetypeideach, v_packagetypeideach,'Northwind','1/12 scale', 14, 1, false, NULL, 15,230,343.85, 15,'Suits child to 20 kg', NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (73,'Ride on vintage American toy coupe (Red) 1/12 scale', v_supplieridnorthwind, v_coloridred, v_packagetypeideach, v_packagetypeideach,'Northwind','1/12 scale', 14, 1, false, NULL, 15,285,426.08, 18,'Suits child to 20 kg', NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (74,'Ride on vintage American toy coupe (Black) 1/12 scale', v_supplieridnorthwind, v_coloridblack, v_packagetypeideach, v_packagetypeideach,'Northwind','1/12 scale', 14, 1, false, NULL, 15,285,426.08, 18,'Suits child to 20 kg', NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (75,'Ride on big wheel monster truck (Black) 1/12 scale', v_supplieridnorthwind, v_coloridblack, v_packagetypeideach, v_packagetypeideach,'Northwind','1/12 scale', 14, 1, false, NULL, 15,345,515.78,21,'Suits child to 20 kg', NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (76,'The Gu red shirt XML tag t-shirt (White) 3XS', v_supplieridfabrikam, v_coloridwhite, v_packagetypeideach, v_packagetypeidcarton, NULL,'3XS',7, 12, false, NULL, 15, 18,26.91,0.25, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (77,'The Gu red shirt XML tag t-shirt (White) XXS', v_supplieridfabrikam, v_coloridwhite, v_packagetypeideach, v_packagetypeidcarton, NULL,'XXS',7, 12, false, NULL, 15, 18,26.91,0.25, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (78,'The Gu red shirt XML tag t-shirt (White) XS', v_supplieridfabrikam, v_coloridwhite, v_packagetypeideach, v_packagetypeidcarton, NULL,'XS',7, 12, false, NULL, 15, 18,26.91,0.25, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (79,'The Gu red shirt XML tag t-shirt (White) S', v_supplieridfabrikam, v_coloridwhite, v_packagetypeideach, v_packagetypeidcarton, NULL,'S',7, 12, false, NULL, 15, 18,26.91,0.3, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (80,'The Gu red shirt XML tag t-shirt (White) M', v_supplieridfabrikam, v_coloridwhite, v_packagetypeideach, v_packagetypeidcarton, NULL,'M',7, 12, false, NULL, 15, 18,26.91,0.35, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (81,'The Gu red shirt XML tag t-shirt (White) L', v_supplieridfabrikam, v_coloridwhite, v_packagetypeideach, v_packagetypeidcarton, NULL,'L',7, 12, false, NULL, 15, 18,26.91,0.35, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (82,'The Gu red shirt XML tag t-shirt (White) XL', v_supplieridfabrikam, v_coloridwhite, v_packagetypeideach, v_packagetypeidcarton, NULL,'XL',7, 12, false, NULL, 15, 18,26.91,0.35, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (83,'The Gu red shirt XML tag t-shirt (White) XXL', v_supplieridfabrikam, v_coloridwhite, v_packagetypeideach, v_packagetypeidcarton, NULL,'XXL',7, 12, false, NULL, 15, 18,26.91,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (84,'The Gu red shirt XML tag t-shirt (White) 3XL', v_supplieridfabrikam, v_coloridwhite, v_packagetypeideach, v_packagetypeidcarton, NULL,'3XL',7, 12, false, NULL, 15, 18,26.91,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (85,'The Gu red shirt XML tag t-shirt (White) 4XL', v_supplieridfabrikam, v_coloridwhite, v_packagetypeideach, v_packagetypeidcarton, NULL,'4XL',7, 12, false, NULL, 15, 18,26.91,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (86,'The Gu red shirt XML tag t-shirt (White) 5XL', v_supplieridfabrikam, v_coloridwhite, v_packagetypeideach, v_packagetypeidcarton, NULL,'5XL',7, 12, false, NULL, 15, 18,26.91,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (87,'The Gu red shirt XML tag t-shirt (White) 6XL', v_supplieridfabrikam, v_coloridwhite, v_packagetypeideach, v_packagetypeidcarton, NULL,'6XL',7, 12, false, NULL, 15, 18,26.91,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (88,'The Gu red shirt XML tag t-shirt (White) 7XL', v_supplieridfabrikam, v_coloridwhite, v_packagetypeideach, v_packagetypeidcarton, NULL,'7XL',7, 12, false, NULL, 15, 18,26.91,0.45, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (89,'The Gu red shirt XML tag t-shirt (Black) 3XS', v_supplieridfabrikam, v_coloridblack, v_packagetypeideach, v_packagetypeidcarton, NULL,'3XS',7, 12, false, NULL, 15, 18,26.91,0.25, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (90,'The Gu red shirt XML tag t-shirt (Black) XXS', v_supplieridfabrikam, v_coloridblack, v_packagetypeideach, v_packagetypeidcarton, NULL,'XXS',7, 12, false, NULL, 15, 18,26.91,0.25, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (91,'The Gu red shirt XML tag t-shirt (Black) XS', v_supplieridfabrikam, v_coloridblack, v_packagetypeideach, v_packagetypeidcarton, NULL,'XS',7, 12, false, NULL, 15, 18,26.91,0.25, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (92,'The Gu red shirt XML tag t-shirt (Black) S', v_supplieridfabrikam, v_coloridblack, v_packagetypeideach, v_packagetypeidcarton, NULL,'S',7, 12, false, NULL, 15, 18,26.91,0.3, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (93,'The Gu red shirt XML tag t-shirt (Black) M', v_supplieridfabrikam, v_coloridblack, v_packagetypeideach, v_packagetypeidcarton, NULL,'M',7, 12, false, NULL, 15, 18,26.91,0.35, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (94,'The Gu red shirt XML tag t-shirt (Black) L', v_supplieridfabrikam, v_coloridblack, v_packagetypeideach, v_packagetypeidcarton, NULL,'L',7, 12, false, NULL, 15, 18,26.91,0.35, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (95,'The Gu red shirt XML tag t-shirt (Black) XL', v_supplieridfabrikam, v_coloridblack, v_packagetypeideach, v_packagetypeidcarton, NULL,'XL',7, 12, false, NULL, 15, 18,26.91,0.35, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (96,'The Gu red shirt XML tag t-shirt (Black) XXL', v_supplieridfabrikam, v_coloridblack, v_packagetypeideach, v_packagetypeidcarton, NULL,'XXL',7, 12, false, NULL, 15, 18,26.91,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (97,'The Gu red shirt XML tag t-shirt (Black) 3XL', v_supplieridfabrikam, v_coloridblack, v_packagetypeideach, v_packagetypeidcarton, NULL,'3XL',7, 12, false, NULL, 15, 18,26.91,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (98,'The Gu red shirt XML tag t-shirt (Black) 4XL', v_supplieridfabrikam, v_coloridblack, v_packagetypeideach, v_packagetypeidcarton, NULL,'4XL',7, 12, false, NULL, 15, 18,26.91,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (99,'The Gu red shirt XML tag t-shirt (Black) 5XL', v_supplieridfabrikam, v_coloridblack, v_packagetypeideach, v_packagetypeidcarton, NULL,'5XL',7, 12, false, NULL, 15, 18,26.91,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (100,'The Gu red shirt XML tag t-shirt (Black) 6XL', v_supplieridfabrikam, v_coloridblack, v_packagetypeideach, v_packagetypeidcarton, NULL,'6XL',7, 12, false, NULL, 15, 18,26.91,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (101,'The Gu red shirt XML tag t-shirt (Black) 7XL', v_supplieridfabrikam, v_coloridblack, v_packagetypeideach, v_packagetypeidcarton, NULL,'7XL',7, 12, false, NULL, 15, 18,26.91,0.45, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (102,'Alien officer hoodie (Black) XL', v_supplieridfabrikam, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL,'XL', 12, 1, false, NULL, 15,35,52.33,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (103,'Alien officer hoodie (Black) XXL', v_supplieridfabrikam, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL,'XXL', 12, 1, false, NULL, 15,35,52.33,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (104,'Alien officer hoodie (Black) 3XL', v_supplieridfabrikam, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL,'3XL', 12, 1, false, NULL, 15,35,52.33,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (105,'Alien officer hoodie (Black) 4XL', v_supplieridfabrikam, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL,'4XL', 12, 1, false, NULL, 15,35,52.33,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (106,'Alien officer hoodie (Black) 5XL', v_supplieridfabrikam, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL,'5XL', 12, 1, false, NULL, 15,35,52.33,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (107,'Superhero action jacket (Blue) 3XS', v_supplieridfabrikam, v_coloridblue, v_packagetypeideach, v_packagetypeideach, NULL,'3XS', 12, 1, false, NULL, 15,25,37.38,0.3, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (108,'Superhero action jacket (Blue) XXS', v_supplieridfabrikam, v_coloridblue, v_packagetypeideach, v_packagetypeideach, NULL,'XXS', 12, 1, false, NULL, 15,25,37.38,0.3, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (109,'Superhero action jacket (Blue) XS', v_supplieridfabrikam, v_coloridblue, v_packagetypeideach, v_packagetypeideach, NULL,'XS', 12, 1, false, NULL, 15,25,37.38,0.3, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (110,'Superhero action jacket (Blue) S', v_supplieridfabrikam, v_coloridblue, v_packagetypeideach, v_packagetypeideach, NULL,'S', 12, 1, false, NULL, 15,25,37.38,0.3, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (111,'Superhero action jacket (Blue) M', v_supplieridfabrikam, v_coloridblue, v_packagetypeideach, v_packagetypeideach, NULL,'M', 12, 1, false, NULL, 15,30,44.85,0.35, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (112,'Superhero action jacket (Blue) L', v_supplieridfabrikam, v_coloridblue, v_packagetypeideach, v_packagetypeideach, NULL,'L', 12, 1, false, NULL, 15,30,44.85,0.35, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (113,'Superhero action jacket (Blue) XL', v_supplieridfabrikam, v_coloridblue, v_packagetypeideach, v_packagetypeideach, NULL,'XL', 12, 1, false, NULL, 15,30,44.85,0.35, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (114,'Superhero action jacket (Blue) XXL', v_supplieridfabrikam, v_coloridblue, v_packagetypeideach, v_packagetypeideach, NULL,'XXL', 12, 1, false, NULL, 15,30,44.85,0.35, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (115,'Superhero action jacket (Blue) 3XL', v_supplieridfabrikam, v_coloridblue, v_packagetypeideach, v_packagetypeideach, NULL,'3XL', 12, 1, false, NULL, 15,34,50.83,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (116,'Superhero action jacket (Blue) 4XL', v_supplieridfabrikam, v_coloridblue, v_packagetypeideach, v_packagetypeideach, NULL,'4XL', 12, 1, false, NULL, 15,34,50.83,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (117,'Superhero action jacket (Blue) 5XL', v_supplieridfabrikam, v_coloridblue, v_packagetypeideach, v_packagetypeideach, NULL,'5XL', 12, 1, false, NULL, 15,34,50.83,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (118,'Dinosaur battery-powered slippers (Green) S', v_supplieridfabrikam, v_coloridgreen, v_packagetypeideach, v_packagetypeideach, NULL,'S', 12, 1, false, NULL, 15,32,47.84,0.35,'Realistic sound of undergrowth being trampled while walking', NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (119,'Dinosaur battery-powered slippers (Green) M', v_supplieridfabrikam, v_coloridgreen, v_packagetypeideach, v_packagetypeideach, NULL,'M', 12, 1, false, NULL, 15,32,47.84,0.35,'Realistic sound of undergrowth being trampled while walking', NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (120,'Dinosaur battery-powered slippers (Green) L', v_supplieridfabrikam, v_coloridgreen, v_packagetypeideach, v_packagetypeideach, NULL,'L', 12, 1, false, NULL, 15,32,47.84,0.35,'Realistic sound of undergrowth being trampled while walking', NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (121,'Dinosaur battery-powered slippers (Green) XL', v_supplieridfabrikam, v_coloridgreen, v_packagetypeideach, v_packagetypeideach, NULL,'XL', 12, 1, false, NULL, 15,32,47.84,0.4,'Realistic sound of undergrowth being trampled while walking', NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (122,'Ogre battery-powered slippers (Green) S', v_supplieridfabrikam, v_coloridgreen, v_packagetypeideach, v_packagetypeideach, NULL,'S', 12, 1, false, NULL, 15,32,47.84,0.35,'Realistic heavy walking sound', NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (123,'Ogre battery-powered slippers (Green) M', v_supplieridfabrikam, v_coloridgreen, v_packagetypeideach, v_packagetypeideach, NULL,'M', 12, 1, false, NULL, 15,32,47.84,0.35,'Realistic heavy walking sound', NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (124,'Ogre battery-powered slippers (Green) L', v_supplieridfabrikam, v_coloridgreen, v_packagetypeideach, v_packagetypeideach, NULL,'L', 12, 1, false, NULL, 15,32,47.84,0.35,'Realistic heavy walking sound', NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (125,'Ogre battery-powered slippers (Green) XL', v_supplieridfabrikam, v_coloridgreen, v_packagetypeideach, v_packagetypeideach, NULL,'XL', 12, 1, false, NULL, 15,32,47.84,0.4,'Realistic heavy walking sound', NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (126,'Plush shark slippers (Gray) S', v_supplieridfabrikam, v_coloridgray, v_packagetypeideach, v_packagetypeideach, NULL,'S', 12, 1, false, NULL, 15,32,47.84,0.35, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (127,'Plush shark slippers (Gray) M', v_supplieridfabrikam, v_coloridgray, v_packagetypeideach, v_packagetypeideach, NULL,'M', 12, 1, false, NULL, 15,32,47.84,0.35, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (128,'Plush shark slippers (Gray) L', v_supplieridfabrikam, v_coloridgray, v_packagetypeideach, v_packagetypeideach, NULL,'L', 12, 1, false, NULL, 15,32,47.84,0.35, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (129,'Plush shark slippers (Gray) XL', v_supplieridfabrikam, v_coloridgray, v_packagetypeideach, v_packagetypeideach, NULL,'XL', 12, 1, false, NULL, 15,32,47.84,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (130,'Furry gorilla with big eyes slippers (Black) S', v_supplieridfabrikam, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL,'S', 12, 1, false, NULL, 15,32,47.84,0.35, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (131,'Furry gorilla with big eyes slippers (Black) M', v_supplieridfabrikam, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL,'M', 12, 1, false, NULL, 15,32,47.84,0.35, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (132,'Furry gorilla with big eyes slippers (Black) L', v_supplieridfabrikam, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL,'L', 12, 1, false, NULL, 15,32,47.84,0.35, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (133,'Furry gorilla with big eyes slippers (Black) XL', v_supplieridfabrikam, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL,'XL', 12, 1, false, NULL, 15,32,47.84,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (134,'Animal with big feet slippers (Brown) S', v_supplieridfabrikam, v_coloridbrown, v_packagetypeideach, v_packagetypeideach, NULL,'S', 12, 1, false, NULL, 15,32,47.84,0.35, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (135,'Animal with big feet slippers (Brown) M', v_supplieridfabrikam, v_coloridbrown, v_packagetypeideach, v_packagetypeideach, NULL,'M', 12, 1, false, NULL, 15,32,47.84,0.35, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (136,'Animal with big feet slippers (Brown) L', v_supplieridfabrikam, v_coloridbrown, v_packagetypeideach, v_packagetypeideach, NULL,'L', 12, 1, false, NULL, 15,32,47.84,0.35, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (137,'Animal with big feet slippers (Brown) XL', v_supplieridfabrikam, v_coloridbrown, v_packagetypeideach, v_packagetypeideach, NULL,'XL', 12, 1, false, NULL, 15,32,47.84,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (138,'Furry animal socks (Pink) S', v_supplieridfabrikam, v_coloridpink, v_packagetypeidpair, v_packagetypeidpacket, NULL,'S', 12, 12, false, NULL, 15,5,7.48,0.1, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (139,'Furry animal socks (Pink) M', v_supplieridfabrikam, v_coloridpink, v_packagetypeidpair, v_packagetypeidpacket, NULL,'M', 12, 12, false, NULL, 15,5,7.48,0.1, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (140,'Furry animal socks (Pink) L', v_supplieridfabrikam, v_coloridpink, v_packagetypeidpair, v_packagetypeidpacket, NULL,'L', 12, 12, false, NULL, 15,5,7.48,0.1, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (141,'Furry animal socks (Pink) XL', v_supplieridfabrikam, v_coloridpink, v_packagetypeidpair, v_packagetypeidpacket, NULL,'XL', 12, 12, false, NULL, 15,5,7.48,0.1, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (142,'Halloween zombie mask (Light Brown) S', v_supplieridfabrikam, v_coloridlightbrown, v_packagetypeideach, v_packagetypeidcarton, NULL,'S', 12, 12, false, NULL, 15, 18,26.91,0.3, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (143,'Halloween zombie mask (Light Brown) M', v_supplieridfabrikam, v_coloridlightbrown, v_packagetypeideach, v_packagetypeidcarton, NULL,'M', 12, 12, false, NULL, 15, 18,26.91,0.3, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (144,'Halloween zombie mask (Light Brown) L', v_supplieridfabrikam, v_coloridlightbrown, v_packagetypeideach, v_packagetypeidcarton, NULL,'L', 12, 12, false, NULL, 15, 18,26.91,0.3, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (145,'Halloween zombie mask (Light Brown) XL', v_supplieridfabrikam, v_coloridlightbrown, v_packagetypeideach, v_packagetypeidcarton, NULL,'XL', 12, 12, false, NULL, 15, 18,26.91,0.3, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (146,'Halloween skull mask (Gray) S', v_supplieridfabrikam, v_coloridgray, v_packagetypeideach, v_packagetypeidcarton, NULL,'S', 12, 12, false, NULL, 15, 18,26.91,0.3, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (147,'Halloween skull mask (Gray) M', v_supplieridfabrikam, v_coloridgray, v_packagetypeideach, v_packagetypeidcarton, NULL,'M', 12, 12, false, NULL, 15, 18,26.91,0.3, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (148,'Halloween skull mask (Gray) L', v_supplieridfabrikam, v_coloridgray, v_packagetypeideach, v_packagetypeidcarton, NULL,'L', 12, 12, false, NULL, 15, 18,26.91,0.3, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (149,'Halloween skull mask (Gray) XL', v_supplieridfabrikam, v_coloridgray, v_packagetypeideach, v_packagetypeidcarton, NULL,'XL', 12, 12, false, NULL, 15, 18,26.91,0.3, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (150,'Pack of 12 action figures (variety)', v_supplieridcontoso, v_coloridnone, v_packagetypeidpacket, v_packagetypeidpacket, NULL, NULL,2, 1, false, NULL, 15, 16,23.92,0.25, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (151,'Pack of 12 action figures (male)', v_supplieridcontoso, v_coloridnone, v_packagetypeidpacket, v_packagetypeidpacket, NULL, NULL,2, 1, false, NULL, 15, 16,23.92,0.25, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (152,'Pack of 12 action figures (female)', v_supplieridcontoso, v_coloridnone, v_packagetypeidpacket, v_packagetypeidpacket, NULL, NULL,2, 1, false, NULL, 15, 16,23.92,0.25, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (153,'Small sized bubblewrap roll 10m', v_supplieridlitware, v_coloridnone, v_packagetypeideach, v_packagetypeideach, NULL,'10m', 14, 10, false, NULL, 15,4.5,6.73,5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (154,'Medium sized bubblewrap roll 20m', v_supplieridlitware, v_coloridnone, v_packagetypeideach, v_packagetypeideach, NULL,'20m', 14, 10, false, NULL, 15,20,29.9,6, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (155,'Large sized bubblewrap roll 50m', v_supplieridlitware, v_coloridnone, v_packagetypeideach, v_packagetypeideach, NULL,'50m', 14, 10, false, NULL, 15,24,35.88, 10, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (156,'10 mm Double sided bubble wrap 10m', v_supplieridlitware, v_coloridnone, v_packagetypeideach, v_packagetypeideach, NULL,'10m', 14, 10, false, NULL, 15, 15,22.43,5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (157,'10 mm Double sided bubble wrap 20m', v_supplieridlitware, v_coloridnone, v_packagetypeideach, v_packagetypeideach, NULL,'20m', 14, 10, false, NULL, 15,30,44.85,6, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (158,'10 mm Double sided bubble wrap 50m', v_supplieridlitware, v_coloridnone, v_packagetypeideach, v_packagetypeideach, NULL,'50m', 14, 10, false, NULL, 15, 105, 156.98, 10, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (159,'20 mm Double sided bubble wrap 10m', v_supplieridlitware, v_coloridnone, v_packagetypeideach, v_packagetypeideach, NULL,'10m', 14, 10, false, NULL, 15, 18,26.91,5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (160,'20 mm Double sided bubble wrap 20m', v_supplieridlitware, v_coloridnone, v_packagetypeideach, v_packagetypeideach, NULL,'20m', 14, 10, false, NULL, 15,33,49.34,6, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (161,'20 mm Double sided bubble wrap 50m', v_supplieridlitware, v_coloridnone, v_packagetypeideach, v_packagetypeideach, NULL,'50m', 14, 10, false, NULL, 15, 108, 161.46, 10, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (162,'32 mm Double sided bubble wrap 10m', v_supplieridlitware, v_coloridnone, v_packagetypeideach, v_packagetypeideach, NULL,'10m', 14, 10, false, NULL, 15,22,32.89,5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (163,'32 mm Double sided bubble wrap 20m', v_supplieridlitware, v_coloridnone, v_packagetypeideach, v_packagetypeideach, NULL,'20m', 14, 10, false, NULL, 15,37,55.32,6, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (164,'32 mm Double sided bubble wrap 50m', v_supplieridlitware, v_coloridnone, v_packagetypeideach, v_packagetypeideach, NULL,'50m', 14, 10, false, NULL, 15, 112, 167.44, 10, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (165,'10 mm Anti static bubble wrap (Blue) 10m', v_supplieridlitware, v_coloridblue, v_packagetypeideach, v_packagetypeideach, NULL,'10m', 14, 10, false, NULL, 15,26,38.87,5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (166,'10 mm Anti static bubble wrap (Blue) 20m', v_supplieridlitware, v_coloridblue, v_packagetypeideach, v_packagetypeideach, NULL,'20m', 14, 10, false, NULL, 15,42,62.79,6, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (167,'10 mm Anti static bubble wrap (Blue) 50m', v_supplieridlitware, v_coloridblue, v_packagetypeideach, v_packagetypeideach, NULL,'50m', 14, 10, false, NULL, 15,99, 148.01, 10, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (168,'20 mm Anti static bubble wrap (Blue) 10m', v_supplieridlitware, v_coloridblue, v_packagetypeideach, v_packagetypeideach, NULL,'10m', 14, 10, false, NULL, 15,29,43.36,5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (169,'20 mm Anti static bubble wrap (Blue) 20m', v_supplieridlitware, v_coloridblue, v_packagetypeideach, v_packagetypeideach, NULL,'20m', 14, 10, false, NULL, 15,45,67.28,6, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (170,'20 mm Anti static bubble wrap (Blue) 50m', v_supplieridlitware, v_coloridblue, v_packagetypeideach, v_packagetypeideach, NULL,'50m', 14, 10, false, NULL, 15, 102, 152.49, 10, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (171,'32 mm Anti static bubble wrap (Blue) 10m', v_supplieridlitware, v_coloridblue, v_packagetypeideach, v_packagetypeideach, NULL,'10m', 14, 10, false, NULL, 15,32,47.84,5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (172,'32 mm Anti static bubble wrap (Blue) 20m', v_supplieridlitware, v_coloridblue, v_packagetypeideach, v_packagetypeideach, NULL,'20m', 14, 10, false, NULL, 15,48,71.76,6, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (173,'32 mm Anti static bubble wrap (Blue) 50m', v_supplieridlitware, v_coloridblue, v_packagetypeideach, v_packagetypeideach, NULL,'50m', 14, 10, false, NULL, 15, 105, 156.98, 10, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (174,'Bubblewrap dispenser (Black) 1.5m', v_supplieridlitware, v_coloridblack, v_packagetypeideach, v_packagetypeideach, NULL,'1.5m', 14, 1, false, NULL, 15,240,358.8, 10, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (175,'Bubblewrap dispenser (Blue) 1.5m', v_supplieridlitware, v_coloridblue, v_packagetypeideach, v_packagetypeideach, NULL,'1.5m', 14, 1, false, NULL, 15,240,358.8, 10, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (176,'Bubblewrap dispenser (Red) 1.5m', v_supplieridlitware, v_coloridred, v_packagetypeideach, v_packagetypeideach, NULL,'1.5m', 14, 1, false, NULL, 15,240,358.8, 10, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (177,'Shipping carton (Brown) 413x285x187mm', v_supplieridlitware, v_coloridbrown, v_packagetypeideach, v_packagetypeideach, NULL,'413x285x187mm', 14,25, false, NULL, 15, 1.05, 1.57,0.3, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (178,'Shipping carton (Brown) 500x310x310mm', v_supplieridlitware, v_coloridbrown, v_packagetypeideach, v_packagetypeideach, NULL,'500x310x310mm', 14,25, false, NULL, 15,2.55,3.81,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (179,'Shipping carton (Brown) 229x229x229mm', v_supplieridlitware, v_coloridbrown, v_packagetypeideach, v_packagetypeideach, NULL,'229x229x229mm', 14,25, false, NULL, 15, 1.05, 1.57,0.3, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (180,'Shipping carton (Brown) 279x254x217mm', v_supplieridlitware, v_coloridbrown, v_packagetypeideach, v_packagetypeideach, NULL,'279x254x217mm', 14,25, false, NULL, 15, 1.11, 1.66,0.3, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (181,'Shipping carton (Brown) 356x229x229mm', v_supplieridlitware, v_coloridbrown, v_packagetypeideach, v_packagetypeideach, NULL,'356x229x229mm', 14,25, false, NULL, 15, 1.14, 1.7,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (182,'Shipping carton (Brown) 457x279x279mm', v_supplieridlitware, v_coloridbrown, v_packagetypeideach, v_packagetypeideach, NULL,'457x279x279mm', 14,25, false, NULL, 15, 1.28, 1.91,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (183,'Shipping carton (Brown) 480x270x320mm', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'480x270x320mm', 14,25, false, NULL, 15,2.74,4.1,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (184,'Shipping carton (Brown) 305x305x305mm', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'305x305x305mm', 14,25, false, NULL, 15,3.5,5.23,0.3, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (185,'Shipping carton (Brown) 356x356x279mm', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'356x356x279mm', 14,25, false, NULL, 15,2.04,3.05,0.3, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (186,'Shipping carton (Brown) 457x457x457mm', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'457x457x457mm', 14,25, false, NULL, 15,2.1,3.14,0.4, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (187,'Express post box 5kg (White) 350x280x130mm', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'350x280x130mm', 14,25, false, NULL, 15,0.95, 1.42,0.2, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (188,'3 kg Courier post bag (White) 300x190x95mm', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'300x190x95mm', 14,25, false, NULL, 15,0.66,0.99,0.1, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (189,'Clear packaging tape 48mmx75m', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'48mmx75m', 14,26, false, NULL, 15,2.9,4.34,0.5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (190,'Clear packaging tape 48mmx100m', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'48mmx100m', 14,20, false, NULL, 15,3.5,5.23,0.7, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (191,'Black and orange fragile despatch tape 48mmx75m', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'48mmx75m', 14,36, false, NULL, 15,3.7,5.53,0.5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (192,'Black and orange fragile despatch tape 48mmx100m', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'48mmx100m', 14,36, false, NULL, 15,4.1,6.13,0.7, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (193,'Black and orange glass with care despatch tape 48mmx75m', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'48mmx75m', 14,24, false, NULL, 15,3.7,5.53,0.5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (194,'Black and orange glass with care despatch tape  48mmx100m', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'48mmx100m', 14,24, false, NULL, 15,4.1,6.13,0.7, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (195,'Black and orange handle with care despatch tape  48mmx75m', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'48mmx75m', 14,24, false, NULL, 15,3.7,5.53,0.5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (196,'Black and orange handle with care despatch tape  48mmx100m', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'48mmx100m', 14,24, false, NULL, 15,4.1,6.13,0.7, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (197,'Black and orange this way up despatch tape 48mmx75m', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'48mmx75m', 14,24, false, NULL, 15,3.7,5.53,0.5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (198,'Black and orange this way up despatch tape  48mmx100m', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'48mmx100m', 14,24, false, NULL, 15,4.1,6.13,0.7, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (199,'Black and yellow heavy despatch tape  48mmx75m', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'48mmx75m', 14,24, false, NULL, 15,3.7,5.53,0.5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (200,'Black and yellow heavy despatch tape 48mmx100m', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'48mmx100m', 14,24, false, NULL, 15,4.1,6.13,0.7, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (201,'Red and white urgent despatch tape 48mmx75m', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'48mmx75m', 14,24, false, NULL, 15,3.7,5.53,0.5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (202,'Red and white urgent  heavy despatch tape  48mmx100m', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'48mmx100m', 14,24, false, NULL, 15,4.1,6.13,0.7, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (203,'Tape dispenser (Black)', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL, NULL,20, 10, false, NULL, 15,32,47.84, 1, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (204,'Tape dispenser (Red)', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL, NULL,20, 10, false, NULL, 15,32,47.84, 1, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (205,'Tape dispenser (Blue)', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL, NULL,20, 10, false, NULL, 15,32,47.84, 1, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (206,'Permanent marker black 5mm nib (Black) 5mm', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'5mm', 14, 12, false, NULL, 15,2.7,4.04,0.1, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (207,'Permanent marker blue 5mm nib (Blue) 5mm', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'5mm', 14, 12, false, NULL, 15,2.7,4.04,0.1, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (208,'Permanent marker red 5mm nib (Red) 5mm', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'5mm', 14, 12, false, NULL, 15,2.7,4.04,0.1, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (209,'Packing knife with metal insert blade (Yellow) 9mm', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'9mm', 14,5, false, NULL, 15, 1.89,2.83,0.5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (210,'Packing knife with metal insert blade (Yellow) 18mm', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'18mm', 14,5, false, NULL, 15,2.4,3.59,0.5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (211,'Small 9mm replacement blades 9mm', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'9mm', 14, 10, false, NULL, 15,4.1,6.13,0.7, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (212,'Large  replacement blades 18mm', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'18mm', 14, 10, false, NULL, 15,4.3,6.43,0.8, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (213,'Air cushion film 200mmx100mm 325m', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'325m', 14, 1, false, NULL, 15,87, 130.07,5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (214,'Air cushion film 200mmx200mm 325m', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'325m', 14, 1, false, NULL, 15,90, 134.55,6, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (215,'Air cushion machine (Blue)', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL, NULL,20, 1, false, NULL, 15, 1899,2839.01, 10, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (216,'Void fill 100 L bag (White) 100L', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'100L', 14, 10, false, NULL, 15, 12.5, 18.69,0.25, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (217,'Void fill 200 L bag (White) 200L', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'200L', 14, 10, false, NULL, 15,25,37.38,0.5, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (218,'Void fill 300 L bag (White) 300L', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'300L', 14, 10, false, NULL, 15,37.5,56.06,0.75, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime)
, (219,'Void fill 400 L bag (White) 400L', v_supplieridlitware, v_coloridnull, v_packagetypeideach, v_packagetypeideach, NULL,'400L', 14, 10, false, NULL, 15,50,74.75, 1, NULL, NULL, NULL, NULL, 1, v_currentdatetime, v_endoftime);
END;
$body$;
