-- Converted from: wwi-ssdt/wwi-ssdt/DataLoadSimulation/Stored Procedures/AddStockItems.sql
CREATE SCHEMA IF NOT EXISTS dataloadsimulation;

CREATE OR REPLACE FUNCTION dataloadsimulation.add_stock_items(
    p_current_date_time timestamp,
    p_starting_when     timestamp,
    p_end_of_time       timestamp,
    p_is_silent_mode    boolean
) RETURNS void AS $$
BEGIN
    IF CAST(p_current_date_time AS date) = '2022-01-01' THEN
        INSERT INTO warehouse.stockitems ("StockItemID","StockItemName","SupplierID","ColorID","UnitPackageID","OuterPackageID","Brand","Size","LeadTimeDays","QuantityPerOuter","IsChillerStock","Barcode","TaxRate","UnitPrice","RecommendedRetailPrice","TypicalWeightPerUnit","MarketingComments","InternalComments","Photo","CustomFields","LastEditedBy","ValidFrom","ValidTo")
        VALUES (220,'Novelty chilli chocolates 250g',(SELECT "SupplierID" FROM purchasing.suppliers WHERE "SupplierName"='A Datum Corporation'),(SELECT "ColorID" FROM warehouse.colors WHERE "ColorName"='NULL'),(SELECT "PackageTypeID" FROM warehouse.packagetypes WHERE "PackageTypeName"='Bag'),(SELECT "PackageTypeID" FROM warehouse.packagetypes WHERE "PackageTypeName"='Carton'),NULL,'250g',3,24,true,'8302039293929',10,8.55,12.23,0.25,'Watch your friends faces when they eat these',NULL,NULL,NULL,1,p_current_date_time,p_end_of_time);
        INSERT INTO warehouse.stockitems ("StockItemID","StockItemName","SupplierID","ColorID","UnitPackageID","OuterPackageID","Brand","Size","LeadTimeDays","QuantityPerOuter","IsChillerStock","Barcode","TaxRate","UnitPrice","RecommendedRetailPrice","TypicalWeightPerUnit","MarketingComments","InternalComments","Photo","CustomFields","LastEditedBy","ValidFrom","ValidTo")
        VALUES (221,'Novelty chilli chocolates 500g',(SELECT "SupplierID" FROM purchasing.suppliers WHERE "SupplierName"='A Datum Corporation'),(SELECT "ColorID" FROM warehouse.colors WHERE "ColorName"='NULL'),(SELECT "PackageTypeID" FROM warehouse.packagetypes WHERE "PackageTypeName"='Bag'),(SELECT "PackageTypeID" FROM warehouse.packagetypes WHERE "PackageTypeName"='Carton'),NULL,'500g',3,12,true,'8302039293647',10,14.5,20.74,0.5,'Watch your friends faces when they eat these',NULL,NULL,NULL,1,p_current_date_time,p_end_of_time);
        INSERT INTO warehouse.stockitemholdings ("StockItemID","QuantityOnHand","BinLocation","LastStocktakeQuantity","LastCostPrice","ReorderLevel","TargetStockLevel","LastEditedBy","LastEditedWhen") VALUES (220,360,'CH-1',360,4.75,240,500,1,p_current_date_time);
        INSERT INTO warehouse.stockitemholdings ("StockItemID","QuantityOnHand","BinLocation","LastStocktakeQuantity","LastCostPrice","ReorderLevel","TargetStockLevel","LastEditedBy","LastEditedWhen") VALUES (221,12,'CH-2',12,8.75,120,250,1,p_current_date_time);
        INSERT INTO warehouse.stockitemstockgroups ("StockItemID","StockGroupID","LastEditedBy","LastEditedWhen") SELECT 220, sg."StockGroupID", 1, p_current_date_time FROM warehouse.stockgroups AS sg WHERE sg."StockGroupName" IN ('Novelty Items','Edible Novelties');
        INSERT INTO warehouse.stockitemstockgroups ("StockItemID","StockGroupID","LastEditedBy","LastEditedWhen") SELECT 221, sg."StockGroupID", 1, p_current_date_time FROM warehouse.stockgroups AS sg WHERE sg."StockGroupName" IN ('Novelty Items','Edible Novelties');

    ELSIF CAST(p_current_date_time AS date) = '2022-01-02' THEN
        INSERT INTO warehouse.stockitems ("StockItemID","StockItemName","SupplierID","ColorID","UnitPackageID","OuterPackageID","Brand","Size","LeadTimeDays","QuantityPerOuter","IsChillerStock","Barcode","TaxRate","UnitPrice","RecommendedRetailPrice","TypicalWeightPerUnit","MarketingComments","InternalComments","Photo","CustomFields","LastEditedBy","ValidFrom","ValidTo")
        VALUES (222,'Chocolate beetles 250g',(SELECT "SupplierID" FROM purchasing.suppliers WHERE "SupplierName"='A Datum Corporation'),(SELECT "ColorID" FROM warehouse.colors WHERE "ColorName"='NULL'),(SELECT "PackageTypeID" FROM warehouse.packagetypes WHERE "PackageTypeName"='Bag'),(SELECT "PackageTypeID" FROM warehouse.packagetypes WHERE "PackageTypeName"='Carton'),NULL,'250g',3,24,true,'8792838293820',10,8.55,12.23,0.25,'Perfect for your child''s party',NULL,NULL,NULL,1,p_current_date_time,p_end_of_time);
        INSERT INTO warehouse.stockitems ("StockItemID","StockItemName","SupplierID","ColorID","UnitPackageID","OuterPackageID","Brand","Size","LeadTimeDays","QuantityPerOuter","IsChillerStock","Barcode","TaxRate","UnitPrice","RecommendedRetailPrice","TypicalWeightPerUnit","MarketingComments","InternalComments","Photo","CustomFields","LastEditedBy","ValidFrom","ValidTo")
        VALUES (223,'Chocolate echidnas 250g',(SELECT "SupplierID" FROM purchasing.suppliers WHERE "SupplierName"='A Datum Corporation'),(SELECT "ColorID" FROM warehouse.colors WHERE "ColorName"='NULL'),(SELECT "PackageTypeID" FROM warehouse.packagetypes WHERE "PackageTypeName"='Bag'),(SELECT "PackageTypeID" FROM warehouse.packagetypes WHERE "PackageTypeName"='Carton'),NULL,'250g',3,24,true,'8792838293728',10,8.55,12.23,0.25,'Perfect for your child''s party',NULL,NULL,NULL,1,p_current_date_time,p_end_of_time);
        INSERT INTO warehouse.stockitemholdings ("StockItemID","QuantityOnHand","BinLocation","LastStocktakeQuantity","LastCostPrice","ReorderLevel","TargetStockLevel","LastEditedBy","LastEditedWhen") VALUES (222,120,'CH-3',120,4.75,240,500,1,p_current_date_time);
        INSERT INTO warehouse.stockitemholdings ("StockItemID","QuantityOnHand","BinLocation","LastStocktakeQuantity","LastCostPrice","ReorderLevel","TargetStockLevel","LastEditedBy","LastEditedWhen") VALUES (223,120,'CH-4',120,4.75,240,500,1,p_current_date_time);
        INSERT INTO warehouse.stockitemstockgroups ("StockItemID","StockGroupID","LastEditedBy","LastEditedWhen") SELECT 222, sg."StockGroupID", 1, p_current_date_time FROM warehouse.stockgroups AS sg WHERE sg."StockGroupName" IN ('Novelty Items','Edible Novelties');
        INSERT INTO warehouse.stockitemstockgroups ("StockItemID","StockGroupID","LastEditedBy","LastEditedWhen") SELECT 223, sg."StockGroupID", 1, p_current_date_time FROM warehouse.stockgroups AS sg WHERE sg."StockGroupName" IN ('Novelty Items','Edible Novelties');

    ELSIF CAST(p_current_date_time AS date) = '2022-01-04' THEN
        INSERT INTO warehouse.stockitems ("StockItemID","StockItemName","SupplierID","ColorID","UnitPackageID","OuterPackageID","Brand","Size","LeadTimeDays","QuantityPerOuter","IsChillerStock","Barcode","TaxRate","UnitPrice","RecommendedRetailPrice","TypicalWeightPerUnit","MarketingComments","InternalComments","Photo","CustomFields","LastEditedBy","ValidFrom","ValidTo")
        VALUES (224,'Chocolate frogs 250g',(SELECT "SupplierID" FROM purchasing.suppliers WHERE "SupplierName"='A Datum Corporation'),(SELECT "ColorID" FROM warehouse.colors WHERE "ColorName"='NULL'),(SELECT "PackageTypeID" FROM warehouse.packagetypes WHERE "PackageTypeName"='Bag'),(SELECT "PackageTypeID" FROM warehouse.packagetypes WHERE "PackageTypeName"='Carton'),NULL,'250g',3,24,true,'8792838293987',10,8.55,12.23,0.25,'Perfect for your child''s party',NULL,NULL,NULL,1,p_current_date_time,p_end_of_time);
        INSERT INTO warehouse.stockitems ("StockItemID","StockItemName","SupplierID","ColorID","UnitPackageID","OuterPackageID","Brand","Size","LeadTimeDays","QuantityPerOuter","IsChillerStock","Barcode","TaxRate","UnitPrice","RecommendedRetailPrice","TypicalWeightPerUnit","MarketingComments","InternalComments","Photo","CustomFields","LastEditedBy","ValidFrom","ValidTo")
        VALUES (225,'Chocolate sharks 250g',(SELECT "SupplierID" FROM purchasing.suppliers WHERE "SupplierName"='A Datum Corporation'),(SELECT "ColorID" FROM warehouse.colors WHERE "ColorName"='NULL'),(SELECT "PackageTypeID" FROM warehouse.packagetypes WHERE "PackageTypeName"='Bag'),(SELECT "PackageTypeID" FROM warehouse.packagetypes WHERE "PackageTypeName"='Carton'),NULL,'250g',3,24,true,'8792838293234',10,8.55,12.23,0.25,'Perfect for your child''s party',NULL,NULL,NULL,1,p_current_date_time,p_end_of_time);
        INSERT INTO warehouse.stockitemholdings ("StockItemID","QuantityOnHand","BinLocation","LastStocktakeQuantity","LastCostPrice","ReorderLevel","TargetStockLevel","LastEditedBy","LastEditedWhen") VALUES (224,144,'CH-5',144,4.75,240,500,1,p_current_date_time);
        INSERT INTO warehouse.stockitemholdings ("StockItemID","QuantityOnHand","BinLocation","LastStocktakeQuantity","LastCostPrice","ReorderLevel","TargetStockLevel","LastEditedBy","LastEditedWhen") VALUES (225,160,'CH-6',160,4.75,240,500,1,p_current_date_time);
        INSERT INTO warehouse.stockitemstockgroups ("StockItemID","StockGroupID","LastEditedBy","LastEditedWhen") SELECT 224, sg."StockGroupID", 1, p_current_date_time FROM warehouse.stockgroups AS sg WHERE sg."StockGroupName" IN ('Novelty Items','Edible Novelties');
        INSERT INTO warehouse.stockitemstockgroups ("StockItemID","StockGroupID","LastEditedBy","LastEditedWhen") SELECT 225, sg."StockGroupID", 1, p_current_date_time FROM warehouse.stockgroups AS sg WHERE sg."StockGroupName" IN ('Novelty Items','Edible Novelties');

    ELSIF CAST(p_current_date_time AS date) = '2022-01-05' THEN
        INSERT INTO warehouse.stockitems ("StockItemID","StockItemName","SupplierID","ColorID","UnitPackageID","OuterPackageID","Brand","Size","LeadTimeDays","QuantityPerOuter","IsChillerStock","Barcode","TaxRate","UnitPrice","RecommendedRetailPrice","TypicalWeightPerUnit","MarketingComments","InternalComments","Photo","CustomFields","LastEditedBy","ValidFrom","ValidTo")
        VALUES (226,'White chocolate snow balls 250g',(SELECT "SupplierID" FROM purchasing.suppliers WHERE "SupplierName"='A Datum Corporation'),(SELECT "ColorID" FROM warehouse.colors WHERE "ColorName"='NULL'),(SELECT "PackageTypeID" FROM warehouse.packagetypes WHERE "PackageTypeName"='Bag'),(SELECT "PackageTypeID" FROM warehouse.packagetypes WHERE "PackageTypeName"='Carton'),NULL,'250g',3,24,true,'8792838293236',10,8.55,12.23,0.25,'Perfect for your child''s party',NULL,NULL,NULL,1,p_current_date_time,p_end_of_time);
        INSERT INTO warehouse.stockitems ("StockItemID","StockItemName","SupplierID","ColorID","UnitPackageID","OuterPackageID","Brand","Size","LeadTimeDays","QuantityPerOuter","IsChillerStock","Barcode","TaxRate","UnitPrice","RecommendedRetailPrice","TypicalWeightPerUnit","MarketingComments","InternalComments","Photo","CustomFields","LastEditedBy","ValidFrom","ValidTo")
        VALUES (227,'White chocolate moon rocks 250g',(SELECT "SupplierID" FROM purchasing.suppliers WHERE "SupplierName"='A Datum Corporation'),(SELECT "ColorID" FROM warehouse.colors WHERE "ColorName"='NULL'),(SELECT "PackageTypeID" FROM warehouse.packagetypes WHERE "PackageTypeName"='Bag'),(SELECT "PackageTypeID" FROM warehouse.packagetypes WHERE "PackageTypeName"='Carton'),NULL,'250g',3,24,true,'8792838293289',10,8.55,12.23,0.25,'Perfect for your child''s party',NULL,NULL,NULL,1,p_current_date_time,p_end_of_time);
        INSERT INTO warehouse.stockitemholdings ("StockItemID","QuantityOnHand","BinLocation","LastStocktakeQuantity","LastCostPrice","ReorderLevel","TargetStockLevel","LastEditedBy","LastEditedWhen") VALUES (226,24,'CH-7',24,4.75,240,500,1,p_current_date_time);
        INSERT INTO warehouse.stockitemholdings ("StockItemID","QuantityOnHand","BinLocation","LastStocktakeQuantity","LastCostPrice","ReorderLevel","TargetStockLevel","LastEditedBy","LastEditedWhen") VALUES (227,48,'CH-8',48,4.75,240,500,1,p_current_date_time);
        INSERT INTO warehouse.stockitemstockgroups ("StockItemID","StockGroupID","LastEditedBy","LastEditedWhen") SELECT 226, sg."StockGroupID", 1, p_current_date_time FROM warehouse.stockgroups AS sg WHERE sg."StockGroupName" IN ('Novelty Items','Edible Novelties');
        INSERT INTO warehouse.stockitemstockgroups ("StockItemID","StockGroupID","LastEditedBy","LastEditedWhen") SELECT 227, sg."StockGroupID", 1, p_current_date_time FROM warehouse.stockgroups AS sg WHERE sg."StockGroupName" IN ('Novelty Items','Edible Novelties');
    END IF;
END;
$$ LANGUAGE plpgsql;
